### ISSUE TITLE
[FEATURE] Artifacts

### ISSUE THREAD

**Issue by Mr00Anderson** [junkdog/artemis-odb#583] opened 2019-05-31 17:07 UTC
Putting this as a place holder. Do we just need a pipeline setup to run builds for nightly on changes? Would like to be able to use the most recent snapshot. Been having issues trying to build from sources in gradle.

**Comment by DaanVanYperen** [comment] 2019-05-31 17:14
Duplicate of #545

**Comment by Mr00Anderson** [comment] 2019-05-31 17:21
Ouch. Forgot due diligence on this one!

**Closed** 2019-05-31 17:21 UTC
Labels: feature-request
